DELETE http://localhost:8080/api/v1/measurements/69fa139c6c8c8fc07871a0fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZrb3JudXNoZW5rb0BnbWFpbC5jb20iLCJpZCI6IjY5Zjc1YzYzNWJlYjAwNmNhNTRjYTZjZSIsImlhdCI6MTc3ODE2NDIxMiwiZXhwIjoxNzc4MTY1MTEyfQ.JgHsq7wIcdcrucQpdLr1aRafza3WFaqftqwbFomKaRI